### ISSUE TITLE
npm i 后部署 laravel 提示 socket hang up

### ISSUE THREAD

**Issue by hundan2020** [serverless-components/tencent-laravel#13]
按照这篇教程<https://registry.serverless.com/package/laravel>进行的部署，完全按教程执行，可以正常deploy

![image](https://user-images.githubusercontent.com/9510938/87226040-bb802d00-c3c3-11ea-9050-83ac39a4ab7f.png)

但是进行 npm i 后，再进行部署，提示 socket hang up

![image](https://user-images.githubusercontent.com/9510938/87226083-131e9880-c3c4-11ea-90bd-93ade508b66c.png)

猜测可能和 node_modules有关，加入到配置的 exclude 后，依然错误

![image](https://user-images.githubusercontent.com/9510938/87226127-655fb980-c3c4-11ea-8cb5-c3041a9b9099.png)

根目录删除 node_modules 后恢复正常 deploy 

因此认为可能是`serverless`或者`tencent-laravel`的问题，希望得到解答 

下方是系统相关信息 

`sls -v`

```
  Serverless Error ---------------------------------------

  "service" property is missing in serverless.yml

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              12.16.3
     Framework Version:         1.74.1
     Plugin Version:            3.6.15
     SDK Version:               2.3.1
     Components Version:        2.31.12
```

`php -v`

```
PHP 7.3.18 (cli) (built: May 12 2020 10:54:33) ( NTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.18, Copyright (c) 1998-2018 Zend Technologies
```

`php artisan -v`

```
Laravel Framework 7.19.1
```

**Comment by tinafangkunding** [comment]
收到，socket hang up的问题已经有专门 issue 在跟进，感谢您的反馈 ！ @hkbarton 辛苦一起看一下

**Comment by hkbarton** [comment]
hi @hundan2020 这个问题稳定出现吗？还是说偶尔出现，我注意到截图中已经上传了12.9mb的代码，如果这个问题稳定出现，是否每次都是在上传到大致同样位置的时候出现？还是说每次情况不太一致？

**Comment by hundan2020** [comment]
@hkbarton 

复测了三次，位置大致相同

![image](https://user-images.githubusercontent.com/9510938/87385411-944a7b00-c5d0-11ea-9e3e-1c968f20a447.png)

![image](https://user-images.githubusercontent.com/9510938/87385609-1175f000-c5d1-11ea-95fd-669ab79638f6.png)

![image](https://user-images.githubusercontent.com/9510938/87385710-53069b00-c5d1-11ea-8c1a-d36b6ca80ef3.png)

移除node_modules后，位置见图

![image](https://user-images.githubusercontent.com/9510938/87385841-af69ba80-c5d1-11ea-8136-999602b9ea49.png)

**Comment by hkbarton** [comment]
@hundan2020 you can update your client by `npm i -g serverless` and try again now.
