### ISSUE TITLE
Php7环境的版本是不是随机的？demo的composer.json php>7.2.5 过了，自己部署的时候挂了

### ISSUE THREAD

**Issue by neyio** [serverless-components/tencent-laravel#24]
Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.2.5". You are running 7.2.2. in /var/user/vendor/composer/platform_check.php on line 24

**Comment by yugasun** [comment]
这个是云函数 Php7 运行环境版本不匹配导致的，可以在执行 composer 安装时，添加 `--ignore-platform-reqs` 参数，如下：

```bash
composer install --ignore-platform-reqs
```

参考 https://stackoverflow.com/questions/65754407/composer-detected-issues-in-your-platform-your-composer-dependencies-require-a/66616566#66616566

**Comment by wzxaini9** [comment]
所以我如果在云函数里使用的PHP7.2.2后的新写法函数啥的是不是就报错了？

**Comment by yugasun** [comment]
@wzxaini9 是的

**Comment by wzxaini9** [comment]
那能升级下云函数的环境吗？
现在PHP8.0.8都有了。。
起码出个7.4.21的环境吧。

**Comment by yugasun** [comment]
@wzxaini9 感谢建议，这个我帮忙反馈下
