### ISSUE TITLE
如何使用触发器

### ISSUE THREAD

**Issue by wzxaini9** [serverless-components/tencent-laravel#26]
设置了一个触发器。。。如何启动  artisan 呢？
希望官网给一个demo。
能启动的话定时任务就没问题了。
![image](https://user-images.githubusercontent.com/7598438/124552780-8daeb680-de66-11eb-8555-d36b60ca9d9d.png)

**Comment by yugasun** [comment]
Web 框架暂只支持 `API 网关触发器`
