### ISSUE TITLE
laravel5.5版本会出现Please provide a valid cache path的bug

### ISSUE THREAD

**Issue by junler** [serverless-components/tencent-laravel#3]
在Laravel Framework 5.5.44中，根据安装步骤提供的.env配置好后，还需要修改config/view.php文件中的compiled为 $_ENV['VIEW_COMPILED_PATH'] ?? realpath(storage_path('framework/views')),

**Comment by tinafangkunding** [comment]
收到， @yugasun  辛苦帮看一下哈

**Comment by yugasun** [comment]
感谢反馈，目前组件兼容 `laravel >= 6.0`，针对低版本用户，可能存在一些缓存处理问题，这里后续会新增说明。
